/**
 * Nintendo maker/licensee codes (2-character ASCII).
 * Used in NDS ROM headers at offset 0x10-0x11.
 *
 * Source: devkitPro ndstool ndscodes.cpp (GPL-3.0), cross-referenced with
 * Pan Docs (gbdev.io) and GBATEK.
 */
export const MAKER_CODES: Record<string, string> = {
  "01": "Nintendo",
  "02": "Rocket Games",
  "03": "Imagineer",
  "04": "Gray Matter",
  "05": "Zamuse",
  "06": "Falcom",
  "07": "Enix",
  "08": "Capcom",
  "09": "Hot B",
  "0A": "Jaleco",
  "0B": "Coconuts Japan",
  "0C": "Coconuts Japan/G.X.Media",
  "0D": "Micronet",
  "0E": "Technos",
  "0F": "Mebio Software",
  "0G": "Shouei System",
  "0H": "Starfish",
  "0J": "Mitsui Fudosan/Dentsu",
  "0L": "Warashi",
  "0N": "Nowpro",
  "0P": "Game Village",
  "12": "Infocom",
  "13": "Electronic Arts Japan",
  "15": "Cobra Team",
  "16": "Human/Field",
  "17": "KOEI",
  "18": "Hudson Soft",
  "19": "S.C.P.",
  "1A": "Yanoman",
  "1C": "Tecmo",
  "1D": "Japan Glary Business",
  "1E": "Forum/OpenSystem",
  "1F": "Virgin Games",
  "1G": "SMDE",
  "1J": "Daikokudenki",
  "1P": "Creatures",
  "1Q": "TDK Deep Impression",
  "20": "KSS",
  "21": "Sunsoft",
  "22": "POW/VR 1 Japan",
  "23": "Micro World",
  "25": "San-X",
  "26": "Enix",
  "27": "Loriciel/Electro Brain",
  "28": "Kemco Japan",
  "29": "Seta",
  "2A": "Culture Brain",
  "2C": "Palsoft",
  "2D": "Visit",
  "2E": "Intec",
  "2F": "System Sacom",
  "2G": "Poppo",
  "2H": "Ubisoft Japan",
  "2J": "Media Works",
  "2K": "NEC InterChannel",
  "2L": "Tam",
  "2M": "Jordan",
  "2N": "Smilesoft",
  "2Q": "Mediakite",
  "30": "Viacom",
  "31": "Carrozzeria",
  "32": "Dynamic",
  "34": "Magifact",
  "35": "Hect",
  "36": "Codemasters",
  "37": "Taito/GAGA",
  "38": "Laguna",
  "39": "Telstar/Event/Taito",
  "3B": "Arcade Zone",
  "3C": "Entertainment International",
  "3D": "Loriciel",
  "3E": "Gremlin Graphics",
  "3F": "K.Amusement Leasing",
  "40": "Seika",
  "41": "Ubisoft",
  "42": "Sunsoft US",
  "44": "Life Fitness",
  "46": "System 3",
  "47": "Spectrum Holobyte",
  "49": "IREM",
  "4B": "Raya Systems",
  "4C": "Renovation Products",
  "4D": "Malibu Games",
  "4F": "Eidos",
  "4G": "Playmates Interactive",
  "4J": "Fox Interactive",
  "4K": "Time Warner Interactive",
  "4Q": "Disney Interactive",
  "4S": "Black Pearl",
  "4U": "Advanced Productions",
  "4X": "GT Interactive",
  "4Y": "Rare",
  "4Z": "Crave Entertainment",
  "50": "Absolute Entertainment",
  "51": "Acclaim",
  "52": "Activision",
  "53": "American Sammy",
  "54": "Take 2 Interactive",
  "55": "Hi Tech",
  "56": "LJN",
  "57": "Matchbox",
  "58": "Mattel",
  "59": "Milton Bradley",
  "5A": "Mindscape",
  "5B": "Romstar",
  "5C": "Taxan",
  "5D": "Midway",
  "5F": "American Softworks",
  "5G": "Majesco",
  "5H": "3DO",
  "5K": "Hasbro",
  "5L": "NewKidCo",
  "5M": "Telegames",
  "5N": "Metro3D",
  "5P": "Vatical Entertainment",
  "5Q": "LEGO Media",
  "5S": "Xicat Interactive",
  "5T": "Cryo Interactive",
  "5W": "Red Storm Entertainment",
  "5X": "Microids",
  "5Z": "Conspiracy/Swing",
  "60": "Titus",
  "61": "Virgin Interactive",
  "62": "Maxis",
  "64": "LucasArts",
  "67": "Ocean",
  "69": "Electronic Arts",
  "6B": "Laser Beam",
  "6E": "Elite Systems",
  "6F": "Electro Brain",
  "6G": "The Learning Company",
  "6H": "BBC",
  "6J": "Software 2000",
  "6L": "BAM! Entertainment",
  "6M": "Studio 3",
  "6Q": "Classified Games",
  "6S": "TDK Mediactive",
  "6U": "DreamCatcher",
  "6V": "JoWood Productions",
  "6W": "Sega",
  "6X": "Wannado Edition",
  "6Y": "LSP",
  "6Z": "ITE Media",
  "70": "Infogrames",
  "71": "Interplay",
  "72": "JVC",
  "73": "Parker Brothers",
  "75": "Sales Curve",
  "78": "THQ",
  "79": "Accolade",
  "7A": "Triffix Entertainment",
  "7C": "Microprose",
  "7D": "Sierra",
  "7F": "Kemco",
  "7G": "Rage Software",
  "7H": "Encore",
  "7J": "Zoo Digital",
  "7K": "BVM",
  "7L": "Simon & Schuster",
  "7M": "Asmik Ace",
  "7N": "Empire Interactive",
  "7Q": "Jester Interactive",
  "7T": "Scholastic",
  "7U": "Ignition Entertainment",
  "7W": "Stadlbauer",
  "80": "Misawa",
  "81": "Teichiku",
  "82": "Namco",
  "83": "LOZC",
  "84": "KOEI",
  "86": "Tokuma Shoten",
  "87": "Tsukuda Original",
  "88": "DATAM-Polystar",
  "8B": "Bulletproof Software",
  "8C": "Vic Tokai",
  "8E": "Character Soft",
  "8F": "I'Max",
  "8G": "Saurus",
  "8J": "General Entertainment",
  "8N": "Success",
  "8P": "Sega Japan",
  "90": "Takara Amusement",
  "91": "Chunsoft",
  "92": "Video System",
  "93": "BEC",
  "95": "Varie",
  "96": "Yonezawa/S'pal",
  "97": "Kaneko",
  "99": "Victor Interactive Software",
  "9A": "Nichibutsu",
  "9B": "Tecmo",
  "9C": "Imagineer",
  "9F": "Nova",
  "9G": "Den'Z",
  "9H": "Bottom Up",
  "9J": "TGL",
  "9L": "Hasbro Japan",
  "9N": "Marvelous Entertainment",
  "9P": "Keynet",
  "9Q": "Hands-On Entertainment",
  A0: "Telenet",
  A1: "Hori",
  A4: "Konami",
  A5: "K.Amusement Leasing",
  A6: "Kawada",
  A7: "Takara",
  A9: "Technos Japan",
  AA: "JVC",
  AC: "Toei Animation",
  AD: "Toho",
  AF: "Namco",
  AG: "Media Rings",
  AH: "J-Wing",
  AJ: "Pioneer LDC",
  AK: "KID",
  AL: "Mediafactory",
  AP: "Infogrames Hudson",
  AQ: "Kiratto/Ludic",
  B0: "Acclaim Japan",
  B1: "ASCII/Nexoft",
  B2: "Bandai",
  B4: "Enix",
  B6: "HAL Laboratory",
  B7: "SNK",
  B9: "Pony Canyon",
  BA: "Culture Brain",
  BB: "Sunsoft",
  BC: "Toshiba EMI",
  BD: "Sony Imagesoft",
  BF: "Sammy",
  BG: "Magical",
  BH: "Visco",
  BJ: "Compile",
  BL: "MTO",
  BN: "Sunrise Interactive",
  BP: "Global A Entertainment",
  BQ: "Fuuki",
  C0: "Taito",
  C2: "Kemco",
  C3: "Square",
  C4: "Tokuma Shoten",
  C5: "Data East",
  C6: "Tonkin House",
  C8: "Koei",
  CA: "Konami/Palcom",
  CB: "NTVIC/VAP",
  CC: "Use",
  CD: "Meldac",
  CE: "Pony Canyon",
  CF: "Angel/Sotsu Agency",
  CG: "Yumedia",
  CJ: "Boss",
  CK: "Axela/Crea-Tech",
  CL: "Sekaibunka-Sha",
  CM: "Konami CE Osaka",
  CP: "Enterbrain",
  D0: "Taito/Disco",
  D1: "Sofel",
  D2: "Quest",
  D3: "Sigma",
  D4: "Ask Kodansha",
  D6: "Naxat",
  D7: "Copya System",
  D8: "Capcom",
  D9: "Banpresto",
  DA: "TOMY",
  DB: "LJN Japan",
  DD: "NCS",
  DE: "Human Entertainment",
  DF: "Altron",
  DG: "Jaleco",
  DH: "Gaps",
  DK: "Kodansha",
  DN: "Elf",
  E0: "Jaleco",
  E2: "Yutaka",
  E3: "Varie",
  E4: "T&ESoft",
  E5: "Epoch",
  E7: "Athena",
  E8: "Asmik",
  E9: "Natsume",
  EA: "King Records",
  EB: "Atlus",
  EC: "Epic/Sony Records",
  EE: "IGS",
  EG: "Chatnoir",
  EH: "Right Stuff",
  EL: "Spike",
  EM: "Konami CE Tokyo",
  EN: "Alphadream",
  F0: "A Wave",
  F1: "Motown Software",
  F2: "Left Field Entertainment",
  F3: "Extreme Entertainment",
  F4: "TecMagik",
  F9: "Cybersoft",
  FB: "Psygnosis",
  FE: "Davidson/Western Tech.",
  G1: "PCCW Japan",
  G4: "KiKi",
  G5: "Open Sesame",
  G6: "Sims",
  G7: "Broccoli",
  G8: "Avex",
  G9: "D3 Publisher",
  GB: "Konami CE Japan",
  GD: "Square Enix",
  IH: "Yojigen",
};
